name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2020-09-03
version: '9.0.5'
project: 'drupal'
datestamp: 1599167794
